name: "Deploy to Github Actions"

on:
  push:
    tags: 
      - 'v*'
    #branches: [ master, develop, nuget_package_publish ]
  
env:
  PROJECT_PATH: 'src/ZeeUtils.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/zeesoft2005/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2
      
    - name: 'Check Version'
      shell: powershell
      run: echo ${{ steps.version.outputs.version-without-v }}
      
    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.GPR_KEY }} -s ${{ env.NUGET_SOURCE_URL }}